### ISSUE TITLE
Minipools display an invalid date before validating

### ISSUE THREAD

**Issue by chand1012** [multisig-labs/Panopticon#9]
More information can be found at multisig-labs/app.gogopool.com#535

![image](https://github.com/multisig-labs/Panopticon/assets/3521582/8c45b7f8-d62d-428a-97bb-4e0b4bc4c0f2)

**Comment by 0xju1ie** [comment]
confirmed its still an issue 

![Image](https://github.com/multisig-labs/Panopticon/assets/15642619/5cc9da0b-4bea-492a-b12c-66dc78faaed2)

we should calculate cycle end like we do on the FE minipool table

**Comment by 0xju1ie** [comment]
if while solving this, you add any documentation to the readme that helped you with set-up then that's bonus points ;)
